application: cardkit
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: index.html
  upload: static/index.html

- url: /(.*\.html)
  static_files: \1
  upload: static/.*

- url: /dist/(.*)
  static_files: dist/\1
  upload: static_dist/(.*)

- url: /js/(.*)
  static_files: js/\1
  upload: static/js/(.*)

- url: /css/(.*)
  static_files: css/\1
  upload: static/css/(.*)

- url: /pics/(.*\.(gif|png|jpg))
  static_files: pics/\1
  upload: static/pics/(.*\.(gif|png|jpg))
