application: cardkit
version: 1
runtime: python
api_version: 1

handlers:
- url: /(.*\.html)
  static_files: \1
  upload: static_dist/.*

- url: /dist/(.*)
  static_files: dist/\1

- url: /static/(.*)
  static_files: static/\1
  upload: static_dist/(.*)

- url: /pics/(.*\.(gif|png|jpg))
  static_files: pics/\1
  upload: static_dist/pics/(.*\.(gif|png|jpg))
